name: shoes_commerce_app
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.0.0
  carousel_slider: ^4.0.0
  google_fonts: 2.2.0
  provider: ^6.0.2
  intl: ^0.17.0
  animations: ^2.0.2
  image_picker: ^0.8.4+11
  flutter_staggered_grid_view: ^0.6.1
  staggered_grid_view_flutter: ^0.0.4
  transparent_image: ^2.0.0
  custom_pop_up_menu: ^1.2.3+1
  star_menu: ^2.1.3
  native_context_menu: ^0.2.1+4
  font_awesome_flutter: ^9.2.0
  http: ^0.13.4
  flutter_staggered_animations: ^1.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:

  generate: true
  uses-material-design: true

  
  assets:
    - assets/
    - assets/categories/
    - assets/images/
    - assets/silder/
   
 

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
